QUESTIONS_LIST = ["inclusion criteria analysis for active phase 2 Acute Myleoid Leukemia",
        "inclusion criteria analysis for active phase 2 Acute Lymphocytic Leukemia",
        "inclusion criteria analysis for active phase 2 Adrenal Gland Tumor",
        "inclusion criteria analysis for active phase 2 Anal Cancer",
        "inclusion criteria analysis for active phase 2 Anemia",
        "inclusion criteria analysis for active phase 2 Aplastic Anemia",
        "inclusion criteria analysis for active phase 2 Basal Cell Carcinoma",
        "inclusion criteria analysis for active phase 2 Bladder Cancer",
        "inclusion criteria analysis for active phase 2 Breast Cancer",
        "inclusion criteria analysis for active phase 2 Cervical Cancer",
        "inclusion criteria analysis for active phase 2 Chondrosarcoma",
        "inclusion criteria analysis for active phase 2 Gliosarcoma",
        "inclusion criteria analysis for active phase 2 Colorectal Cancer",
        "inclusion criteria analysis for active phase 2 Endometrial Cancer",
        "inclusion criteria analysis for active phase 2 Esophegal Cancer",
        "inclusion criteria analysis for active phase 2 Ewing Sarcoma",
        "inclusion criteria analysis for active phase 2 Gastric Cancer",
        "inclusion criteria analysis for active phase 2 Glioma",
        "inclusion criteria analysis for active phase 2 Head & Neck Cancers",
        "inclusion criteria analysis for active phase 2 Hodgkins Lympnoma",
        "inclusion criteria analysis for active phase 2 Kidney Cancer",
        "inclusion criteria analysis for active phase 2 Leukemia",
        "inclusion criteria analysis for active phase 2 Medulloblastoma",
        "inclusion criteria analysis for active phase 2 Melanoma",
        "inclusion criteria analysis for active phase 2 Multiple Endocrine Neoplasia",
        "inclusion criteria analysis for active phase 2 Multiple Myeloma",
        "inclusion criteria analysis for active phase 2 Myelodysplatstic Syndromes",
        "inclusion criteria analysis for active phase 2 Myeloproliferative neoplasims",
        "inclusion criteria analysis for active phase 2 Neuroblastoma",
        "inclusion criteria analysis for active phase 2 Neuroendocrine Tumors",
        "inclusion criteria analysis for active phase 2 Non Hodgkins Lymphoma",
        "inclusion criteria analysis for active phase 2 NSCLC",
        "inclusion criteria analysis for active phase 2 Osteosarcoma",
        "inclusion criteria analysis for active phase 2 Ovarian",
        "inclusion criteria analysis for active phase 2 Pancreatic Cancer",
        "inclusion criteria analysis for active phase 2 Prostate Cancer",
        "inclusion criteria analysis for active phase 2 Retinoblastoma",
        "inclusion criteria analysis for active phase 2 Sacoma",
        "inclusion criteria analysis for active phase 2 Small Cell Lung Cancer",
        "inclusion criteria analysis for active phase 2 Stomach Cancer",
        "inclusion criteria analysis for active phase 2 Testicular",
        "inclusion criteria analysis for active phase 2 Thyroid Cancer",
        "inclusion criteria analysis for active phase 2 Utexrine/Vaginal",
        "inclusion criteria analysis for active phase 3 Acute Myleoid Leukemia",
        "inclusion criteria analysis for active phase 3 Acute Lymphocytic Leukemia",
        "inclusion criteria analysis for active phase 3 Adrenal Gland Tumor",
        "inclusion criteria analysis for active phase 3 Anal Cancer",
        "inclusion criteria analysis for active phase 3 Anemia",
        "inclusion criteria analysis for active phase 3 Aplastic Anemia",
        "inclusion criteria analysis for active phase 3 Basal Cell Carcinoma",
        "inclusion criteria analysis for active phase 3 Bladder Cancer",
        "inclusion criteria analysis for active phase 3 Breast Cancer",
        "inclusion criteria analysis for active phase 3 Cervical Cancer",
        "inclusion criteria analysis for active phase 3 Colorectal Cancer",
        "inclusion criteria analysis for active phase 3 Endometrial Cancer",
        "inclusion criteria analysis for active phase 3 Esophegal Cancer",
        "inclusion criteria analysis for active phase 3 Gastric Cancer",
        "inclusion criteria analysis for active phase 3 Glioma",
        "inclusion criteria analysis for active phase 3 Head & Neck Cancers",
        "inclusion criteria analysis for active phase 3 Hodgkins Lympnoma",
        "inclusion criteria analysis for active phase 3 Kidney Cancer",
        "inclusion criteria analysis for active phase 3 Leukemia",
        "inclusion criteria analysis for active phase 3 Melanoma",
        "inclusion criteria analysis for active phase 3 Multiple Endocrine Neoplasia",
        "inclusion criteria analysis for active phase 3 Multiple Myeloma",
        "inclusion criteria analysis for active phase 3 Myelodysplatstic Syndromes",
        "inclusion criteria analysis for active phase 3 Myeloproliferative neoplasims",
        "inclusion criteria analysis for active phase 3 Neuroblastoma",
        "inclusion criteria analysis for active phase 3 Neuroendocrine Tumors",
        "inclusion criteria analysis for active phase 3 Non Hodgkins Lymphoma",
        "inclusion criteria analysis for active phase 3 NSCLC",
        "inclusion criteria analysis for active phase 3 Ovarian",
        "inclusion criteria analysis for active phase 3 Pancreatic Cancer",
        "inclusion criteria analysis for active phase 3 Prostate Cancer",
        "inclusion criteria analysis for active phase 3 Sacoma",
        "inclusion criteria analysis for active phase 3 Small Cell Lung Cancer",
        "inclusion criteria analysis for active phase 3 Stomach Cancer",
        "inclusion criteria analysis for active phase 3 Testicular",
        "inclusion criteria analysis for active phase 3 Thyroid Cancer",
        "inclusion criteria analysis for active phase 3 Utexrine/Vaginal",
        "exclusion criteria analysis for active phase 2 Acute Myleoid Leukemia",
        "exclusion criteria analysis for active phase 2 Acute Lymphocytic Leukemia",
        "exclusion criteria analysis for active phase 2 Adrenal Gland Tumor",
        "exclusion criteria analysis for active phase 2 Anal Cancer",
        "exclusion criteria analysis for active phase 2 Anemia",
        "exclusion criteria analysis for active phase 2 Aplastic Anemia",
        "exclusion criteria analysis for active phase 2 Basal Cell Carcinoma",
        "exclusion criteria analysis for active phase 2 Bladder Cancer",
        "exclusion criteria analysis for active phase 2 Breast Cancer",
        "exclusion criteria analysis for active phase 2 Cervical Cancer",
        "exclusion criteria analysis for active phase 2 Chondrosarcoma",
        "exclusion criteria analysis for active phase 2 Gliosarcoma",
        "exclusion criteria analysis for active phase 2 Colorectal Cancer",
        "exclusion criteria analysis for active phase 2 Endometrial Cancer",
        "exclusion criteria analysis for active phase 2 Esophegal Cancer",
        "exclusion criteria analysis for active phase 2 Ewing Sarcoma",
        "exclusion criteria analysis for active phase 2 Gastric Cancer",
        "exclusion criteria analysis for active phase 2 Glioma",
        "exclusion criteria analysis for active phase 2 Head & Neck Cancers",
        "exclusion criteria analysis for active phase 2 Hodgkins Lympnoma",
        "exclusion criteria analysis for active phase 2 Kidney Cancer",
        "exclusion criteria analysis for active phase 2 Leukemia",
        "exclusion criteria analysis for active phase 2 Medulloblastoma",
        "exclusion criteria analysis for active phase 2 Melanoma",
        "exclusion criteria analysis for active phase 2 Multiple Endocrine Neoplasia",
        "exclusion criteria analysis for active phase 2 Multiple Myeloma",
        "exclusion criteria analysis for active phase 2 Myelodysplatstic Syndromes",
        "exclusion criteria analysis for active phase 2 Myeloproliferative neoplasims",
        "exclusion criteria analysis for active phase 2 Neuroblastoma",
        "exclusion criteria analysis for active phase 2 Neuroendocrine Tumors",
        "exclusion criteria analysis for active phase 2 Non Hodgkins Lymphoma",
        "exclusion criteria analysis for active phase 2 NSCLC",
        "exclusion criteria analysis for active phase 2 Osteosarcoma",
        "exclusion criteria analysis for active phase 2 Ovarian",
        "exclusion criteria analysis for active phase 2 Pancreatic Cancer",
        "exclusion criteria analysis for active phase 2 Prostate Cancer",
        "exclusion criteria analysis for active phase 2 Retinoblastoma",
        "exclusion criteria analysis for active phase 2 Sacoma",
        "exclusion criteria analysis for active phase 2 Small Cell Lung Cancer",
        "exclusion criteria analysis for active phase 2 Stomach Cancer",
        "exclusion criteria analysis for active phase 2 Testicular",
        "exclusion criteria analysis for active phase 2 Thyroid Cancer",
        "exclusion criteria analysis for active phase 2 Utexrine/Vaginal",
        "exclusion criteria analysis for active phase 3 Acute Myleoid Leukemia",
        "exclusion criteria analysis for active phase 3 Acute Lymphocytic Leukemia",
        "exclusion criteria analysis for active phase 3 Adrenal Gland Tumor",
        "exclusion criteria analysis for active phase 3 Anal Cancer",
        "exclusion criteria analysis for active phase 3 Anemia",
        "exclusion criteria analysis for active phase 3 Aplastic Anemia",
        "exclusion criteria analysis for active phase 3 Basal Cell Carcinoma",
        "exclusion criteria analysis for active phase 3 Bladder Cancer",
        "exclusion criteria analysis for active phase 3 Breast Cancer",
        "exclusion criteria analysis for active phase 3 Cervical Cancer",
        "exclusion criteria analysis for active phase 3 Chondrosarcoma",
        "exclusion criteria analysis for active phase 3 Colorectal Cancer",
        "exclusion criteria analysis for active phase 3 Endometrial Cancer",
        "exclusion criteria analysis for active phase 3 Esophegal Cancer",
        "exclusion criteria analysis for active phase 3 Gastric Cancer",
        "exclusion criteria analysis for active phase 3 Glioma",
        "exclusion criteria analysis for active phase 3 Head & Neck Cancers",
        "exclusion criteria analysis for active phase 3 Hodgkins Lympnoma",
        "exclusion criteria analysis for active phase 3 Kidney Cancer",
        "exclusion criteria analysis for active phase 3 Leukemia",
        "exclusion criteria analysis for active phase 3 Melanoma",
        "exclusion criteria analysis for active phase 3 Multiple Endocrine Neoplasia",
        "exclusion criteria analysis for active phase 3 Multiple Myeloma",
        "exclusion criteria analysis for active phase 3 Myelodysplatstic Syndromes",
        "exclusion criteria analysis for active phase 3 Myeloproliferative neoplasims",
        "exclusion criteria analysis for active phase 3 Neuroblastoma",
        "exclusion criteria analysis for active phase 3 Neuroendocrine Tumors",
        "exclusion criteria analysis for active phase 3 Non Hodgkins Lymphoma",
        "exclusion criteria analysis for active phase 3 NSCLC",
        "exclusion criteria analysis for active phase 3 Ovarian",
        "exclusion criteria analysis for active phase 3 Pancreatic Cancer",
        "exclusion criteria analysis for active phase 3 Prostate Cancer",
        "exclusion criteria analysis for active phase 3 Sacoma",
        "exclusion criteria analysis for active phase 3 Small Cell Lung Cancer",
        "exclusion criteria analysis for active phase 3 Stomach Cancer",
        "exclusion criteria analysis for active phase 3 Testicular",
        "exclusion criteria analysis for active phase 3 Thyroid Cancer",
        "exclusion criteria analysis for active phase 3 Utexrine/Vaginal"
    ]

COMMANDS = []
# COMMANDS = ["no answer cache",
#             "no operator cache"]
