QUESTIONS_LIST = [
    "list code information of inclusion criteria analysis for active phase 2 NSCLC trials as json",
    "list code information of inclusion criteria analysis for active phase 2 breast cacner trials as json",
    "list code information of inclusion criteria analysis for active phase 2 colorectal cancer trials as json",
    "list code information of inclusion criteria analysis for active phase 2 pancreatic cancer trials as json",
    "list code information of inclusion criteria analysis for active phase 2 multiple myeloma trials as json",
    "list code information of inclusion criteria analysis for active phase 2 Chronic Myelogenous Leukemia trials as json",
    "list code information of inclusion criteria analysis for active phase 2 Acute Myelogenous Leukemia trials as json",
    "list code information of exclusion criteria analysis for active phase 2 NSCLC trials as json",
    "list code information of exclusion criteria analysis for active phase 2 breast cacner trials as json",
    "list code information of exclusion criteria analysis for active phase 2 prostate cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 2 colorectal cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 2 pancreatic cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 2 multiple myeloma trials as json",
    "list code information of exclusion criteria analysis for active phase 2 Chronic Myelogenous Leukemia trials as json",
    "list code information of exclusion criteria analysis for active phase 2 Acute Myelogenous Leukemia trials as json",
    "list code information of inclusion criteria analysis for active phase 3 NSCLC trials as json",
    "list code information of inclusion criteria analysis for active phase 3 breast cacner trials as json",
    "list code information of inclusion criteria analysis for active phase 3 colorectal cancer trials as json",
    "list code information of inclusion criteria analysis for active phase 3 pancreatic cancer trials as json",
    "list code information of inclusion criteria analysis for active phase 3 multiple myeloma trials as json",
    "list code information of inclusion criteria analysis for active phase 3 Chronic Myelogenous Leukemia trials as json",
    "list code information of inclusion criteria analysis for active phase 3 Acute Myelogenous Leukemia trials as json",
    "list code information of exclusion criteria analysis for active phase 3 NSCLC trials as json",
    "list code information of exclusion criteria analysis for active phase 3 breast cacner trials as json",
    "list code information of exclusion criteria analysis for active phase 3 prostate cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 3 colorectal cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 3 pancreatic cancer trials as json",
    "list code information of exclusion criteria analysis for active phase 3 multiple myeloma trials as json",
    "list code information of exclusion criteria analysis for active phase 3 Chronic Myelogenous Leukemia trials as json",
    "list code information of exclusion criteria analysis for active phase 3 Acute Myelogenous Leukemia trials as json"
    ]

# COMMANDS = []
COMMANDS = ["no answer cache",
            "no operator cache"]
