name: Run unit tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Run tests
        run: |
          pip install pipenv
          pipenv run pip install .

          rm nose2.cfg
          echo "[unittest]
          start-dir = tests
          code-directories = unit
          test-file-pattern = test_*.py" >> nose2.cfg

          pipenv run nose2 -v
